name: CI/CD Pipeline
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t ci-cd-demo .
      - name: Test
        run: docker run -d -p 3000:3000 ci-cd-demo && sleep 5 && curl http://localhost:3000